### ISSUE TITLE
WMF spec should specify track name usage in Subscribe/Publish

### ISSUE THREAD

**Issue by suhasHere** [moq-wg/msf#1]
As per consensus at IETF116, subscribes and publishes happens on Track Names that are fully qualified with a prefix and a suffix.
WMF spec should describe how the track name are formed from the catalog to be used in the control messages.

**Comment by wilaw** [comment]
Agreed. Once we figure out how the MoQTransport defines its addressing and subscriptions, then we can update this WMF spec so that the two are consistent.

**Comment by wilaw** [comment]
Closing since track naming has been resolved in moq-transport and this draft was updated with #12
