### ISSUE TITLE
Develop a timeline track with capacity for timed metadata 

### ISSUE THREAD

**Issue by wilaw** [moq-wg/msf#25]
A special ‘timeline’ track is produced which describes the availability of groups and objects with respect to media time and wallclock time. May also carry media time events which can be used by the player in constructing a UI, for example  “Goal”, “Penalty”.  This track can be used by the player for seeking to request specific portions of a DVR window in a live stream, or to any portion of a VOD asset. This may be used for advertising insertion at a later date. 

In the proposed structure below, the metadata field may be empty. If present, it must be enclosed inside double quotes and may hold any string data. In this example, JSON and XML metadata entires are shown. 

```
GROUP_ID,OBJECT_ID,WALLCLOCK,MEDIA_PTS,METADATA
0,0,1698351160362,0,
1,0,1698353162,2002,
2,0,1698355164,4004,"{""score":{""England"":0,""Spain"":0}}"
2,8,1698355232,4072,"<Event id='6' presentationTime='4072'><scte35:signal><scte35:binary>/DBhAAAAAAAA///wBQb+qM1E7QBLAhdDVUVJSAAArX+fCAgAAAAALLLXnTUCAAIXQ1VFSUgAACZ/nwgIAAAAACyy150RAAACF0NVRUlIAAAnf58ICAAAAAAsstezEAAAihiGnw==</scte35:binary></scte35:signal></Event>"


```

**Comment by gwendalsimon** [comment]
I like the idea.
Note that some have advocated for KLV as the support for timed metadata for live video. Here is a Demuxed talk about it a couple of years ago https://www.youtube.com/watch?v=-tpLOEjohmw&ab_channel=Demuxed
