### ISSUE TITLE
Multiple catalog format/versions

### ISSUE THREAD

**Issue by kixelated** [moq-wg/msf#7]
In the current draft, the catalog lives at a well-known path with a single format/version. If the consumer does not support this format/version pair, then playback will not work, unless it knows how to request a different catalog instead.

This will make it virtually impossible to deploy new catalog formats and versions. Every consumer MUST support a new format/version before the publisher can use it at the well-known path, otherwise it risks breaking consumers.

**Comment by kixelated** [comment]
I think we need the ability advertise multiple catalogs.

For example:
- CMAF/v0
- CMAF/v1
- CUSTOM/v0

We do need a way to announce supported formats so the client doesn't blindly request them. This could either be delegated to the application, or we could announce available tracks/formats in the transport itself.

**Comment by kixelated** [comment]
And putting the format/version on the wire is a bit strange. The consumer should support a format/version BEFORE receiving it (either via a SUBSCRIBE or PUBLISH). Otherwise it's wasted bandwidth or a wasted round-trip.

**Comment by wilaw** [comment]
> Every consumer MUST support a new format/version before the publisher can use it at the well-known path, otherwise it risks breaking consumers.

This is how HLS, DASH, RTMP, SRT, etc work today. The client already knows the format it wants to receive. I'm not sure we need to create a system that advertises multiple formats to a 'blind' client which then chooses one it recognizes. 99.9% of the time the client will already know, and yet we would have carry out this meta-format discovery step with each stream start.

If someone really DID want to create a super-set of other formats, they could create a streaming format whose CATALOG simply lists the other available format types and the track names on which they could be requested. The client would then subscribe to the main CATALOG, get the list of streaming formats, subscribe to that sub-catalog track, get the list of track IDs and then start subscribing.

**Comment by wilaw** [comment]
A common catalog format is now available at https://datatracker.ietf.org/doc/draft-wilaw-moq-catalogformat/

**Comment by wilaw** [comment]
Closing as fixed by Common Catalog Format. [Example 3.4.11](https://moq-wg.github.io/catalog-format/draft-wilaw-moq-catalogformat.html#name-a-catalog-referencing-catal) 

```
{
  "version": 1,
  "sequence": 0,
  "catalogs": [
    {
      "name": "catalog-for-format-one",
      "namespace": "sports.example.com/games/08-08-23/live",
      "streamingFormat":1,
      "streamingFormatVersion": "0.2"
    },
    {
      "name": "catalog-for-format-five",
      "namespace": "chat.example.com/games/08-08-23/chat",
      "streamingFormat":5,
      "streamingFormatVersion": "1.6.2"
    }
  ]
}
```
