### ISSUE TITLE
Publish Race

### ISSUE THREAD

**Issue by kixelated** [moq-wg/msf#9]
> A WMF publisher MUST publish a catalog track object before publishing any media track objects.

The publisher could write the catalog track first with higher priority than any media tracks, however packet loss could mean the media tracks arrive first. Since this is a MUST, would the consumer terminate the connection with an error if this occurs?

The publisher could wait until the catalog track arrives, but how does the publisher implement this? Would it wait for the entire stream to be acknowledged? However, acknowledgements don't guarantee that the stream has been processed (ex. QPACK). We would need an explicit application acknowledgement when the catalog has been processed, which of course incurs a round trip.

This explicit application acknowledgement is basically just a SUBSCRIBE. I would actually prohibit publishing any media tracks if that's the behavior we want.

Alternatively, we could add text that the consumer MAY buffer unknown tracks. If the consumer receives an unknown track, then it can hold onto it until it receives a catalog referencing it. This is an optimization that WebTransport employs but it seems fundamentally required when using PUBLISH.

**Comment by kixelated** [comment]
I'm generally not a fan of the proposed PUBLISH message in Warp transport. It creates these sorts of race conditions and it requires that the publisher knows the consumer's intent. I would like to reduce the RTTs but I think it's premature.

**Comment by wilaw** [comment]
IN thinking this through further, if we assume 1) that a publisher only sends track data in response to a subscribe request (which is the model I prefer but I acknowledge we have not agreed to this yet in the MoQ Base Protocl discussions) and 2) that in order to know what to subscribe to a client must first  read the catalog, then we can remove the MUST as written and instead replace it with a requirement that a publisher always make a CATALOG track available if it has any other media track available. This itself may become a requirement of MOQ base protocol, in which case the WMF would inherit it and we can remove this statement completely from the WMF draft.

**Comment by kixelated** [comment]
Yeah, I left a relevant PR review in: https://github.com/kixelated/warp-draft/pull/123

> Going to -1 this until we talk more about the publish use-case. This feels like PUSH_PROMISE.
>
> The ability to publish is intended to remove a round-trip when the sender already knows the intent of the receiver. There has to be some form of coordination out of the scope of this specification, which automatically rules out generic clients.
>
> If this coordination of intent already exists, then receiver could just SUBSCRIBE immediately. I don't actually think it introduces an RTT because of SETUP currently works, and now is not the time to be nit-picking over startup RTTs anyway.
>
> The cost of PUBLISH is complexity and race conditions. OBJECTs arrive before they were requested, requiring some form of buffering and identification. We also need a way of saying "pls no" if the endpoints actually did not coordinate.

I would propose that the receiver immediately issue a `SUBSCRIBE /catalog` (or another well-known path) to learn about the available tracks if this is not negotiated out-of-band. The SUBSCRIBE could even be sent along with the handshake with my control stream proposal: https://github.com/kixelated/warp-draft/issues/138

**Comment by wilaw** [comment]
The ANNOUNCE message of https://datatracker.ietf.org/doc/draft-lcurley-moq-transport/ address this issue.
